import numpy as np
import Basic as Bsc
from math import log, ceil

"""
Instruction:
  DDTM.py — prepares plaintext sets; computes counts of plaintexts required for a target success probability and writes them to disk.
  Also, it reads the ciphertexts generated by CDTM, compute the counts of ciphertexts and make a decision about the generator of it.
"""

###################################################################################################
####                     Writing the required plaintexts into a text file                      ####
###################################################################################################
def WriteDoc(ptxList: list, Address: str) -> None:
    try:
        if type(ptxList) != list:
            raise TypeError("The first input must be a list of plaintexts.")
        else:
            Address = Address + "\\Plaintexts.txt"
            Len = len(ptxList)
            flag = True
            with open(Address, "w") as f:
                for i in range(0, Len):
                    f.write("0x")
                    for j in range(0, 4):
                        for l in range(0, 4):
                            f.write(Bsc.Int2Hex(ptxList[i][j][l]))
                    f.write("\n")
                    y = round((i + 1) / Len * 100, 2)
                    if abs(y - round(y)) < 0.05 and flag == True:
                        print(f"DDTM: {round(y)}% of the writing has been completed.")
                        flag = False
                    elif abs(y - round(y)) >= 0.05:
                        flag = True
                    else:
                        continue
            f.close()

    except TypeError as e:
        print("Error: Invalid input.", e)

###################################################################################################
####                    Reading blocks from the text file prepared by CDTM                     ####
###################################################################################################
def ReadDoc(Address: str) -> list:
    try:
        if type(Address) != str:
            raise TypeError("The first input must be the address of the target file.")
        else:
            ctxList = []
            Address = Address + "\\Ciphertexts.txt"
            with open(Address, "r") as f:
                Data = f.read()
                f.close()
            Len = len(Data)
            ctr = 0
            ctr2 = 0
            flag = True
            while(ctr < Len):
                if Data[ctr] == "0" and Data[ctr + 1] == "x":
                    ctr += 2
                elif Data[ctr - 2] == "0" and Data[ctr - 1] == "x":
                    ctr3 = 0
                    X = np.array([
                        [0, 0, 0, 0],
                        [0, 0, 0, 0],
                        [0, 0, 0, 0],
                        [0, 0, 0, 0]
                        ], dtype = np.uint8)
                    for i in range(0, 4):
                        for j in range (0, 4):
                            X[i][j] = Bsc.Hex2Int(Data[ctr + ctr3])
                            ctr3 += 1
                    ctr += 16
                    ctxList.append(X.copy())
                elif Data[ctr] == "\n":
                    ctr += 1
                    ctr2 += 1
                else:
                    ctr += 1
                y = round(100 * ctr / Len, 2)
                if abs(y - round(y)) < 0.05 and flag == True:
                    print(f"DDTM: {round(y)}% of the reading has been completed.")
                    flag = False
                elif abs(y - round(y)) >= 0.05:
                    flag = True
                else:
                    continue
            return ctxList

    except TypeError as e:
        print("Error: Invalid input.", e)

###################################################################################################
####                       Preparing and writing the required plaintexts                       ####
###################################################################################################
def DDTM_Write(pr: float, Address: str) -> None:
    try:
        if type(pr) != float or pr < 0.5 or pr >= 1:
            raise ValueError("The input must be a float between 0.5 and 1, with 1 excluded.")
        else:
            N = ceil(256 / 15 * log(1 / ((1 - pr) * 2)))
            print(f"The number of plaintexts required to achieve a success probability of {pr} is: {N}.")
            ptxList = []
            for i in range(0, N):
                X = np.array([
                    [0, 0, 0, 0],
                    [0, 0, 0, 0],
                    [0, 0, 0, 0],
                    [0, 0, 0, 0]
                    ], dtype = np.uint8)
                for j in range (0, 4):
                    for l in range(0, 3):
                        X[j][l] = Bsc.RandInt(0, 15, True)
                for X03 in range(0, 16):
                    X[0][3] = np.uint8(X03)
                    for X13 in range(0, 16):
                        X[1][3] = np.uint8(X13)
                        for X23 in range(0, 16):
                            X[2][3] = np.uint8(X23)
                            for X33 in range(0, 16):
                                X[3][3] = np.uint8(X33)
                                ptxList.append(X.copy())
            WriteDoc(ptxList, Address)

    except ValueError as e:
        print("Error: Invalid input.", e)

###################################################################################################
####        Processing the received data and making decision about the generator of it         ####
###################################################################################################
def DDTM_Decision(pr: int, Address: str) -> bool:
    try:
        if type(pr) != float or pr < 0.5 or pr >= 1:
            raise ValueError("The input must be a float between 0.5 and 1, with 1 excluded.")
        else:
            N = ceil(256 / 15 * log(1 / ((1 - pr) * 2)))
            listData = ReadDoc(Address)
            X = np.zeros((N * 16, 16), dtype = np.uint8)
            ctr = 0
            flag = True
            for i in range(0, N):
                for j in range(0, 65536):
                    for m in range(0, 4):
                        for n in range(0, 4):
                            p = 16 * i + 4 * m + n
                            q = int(listData[ctr][m][n])
                            X[p][q] = 1 - X[p][q]
                    ctr += 1
                    y = round(100 * ctr / (N * 65536), 2)
                    if abs(y - round(y)) < 0.05 and flag == True:
                        print(f"DDTM: {round(y)}% of the processing has been completed.")
                        flag = False
                    elif abs(y - round(y)) >= 0.05:
                        flag = True
                    else:
                        continue
            bHat = False
            Y = np.zeros((N * 16, 1), dtype = np.uint8)
            for i in range(0, N * 16):
                for j in range (0, 16):
                    Y[i] = Y[i] + X[i][j]
                if Y[i] == 2:
                    bHat = True
                    print(f"Received data is generated by a random permutation ", end = "")
                    break
            if bHat:
                print(f"Received data is generated by the mCrypton block cipher ", end = "")
            print(f"-> bHat = {bHat}.")
            return bHat

    except ValueError as e:
        print("Error: Invalid input.", e)